### PR TITLE
postgres/duckdb TIMETZ conversion

### LINKED ISSUE #596: Add support for TIME and TIME_TZ types
### Description

These are the only time related types that we don't support yet. Once supported we can un-exclude these columns: https://github.com/duckdb/pg_duckdb/blob/02ebeaec1b42619fab806fc881e67de0821b380d/test/regression/expected/test_all_types.out#L8-L9

### PR DESCRIPTION
**Pull request by dentiny**
Resolve the second part for https://github.com/duckdb/pg_duckdb/issues/596 (TIMETZ conversion).

Fixes #596

### CODE REVIEW

File: src/pgduckdb_types.cpp [hunk 1]
```diff
@@ -236,6 +236,18 @@ ConvertTimeDatum(const duckdb::Value &value) {
...
 
+static Datum
+ConvertTimeTzDatum(const duckdb::Value &value) {
+	duckdb::dtime_tz_t dt_tz = value.GetValue<duckdb::dtime_tz_t>();
+	const int64_t micros = dt_tz.time().micros;
+	const int32_t tz_offset = dt_tz.offset();
+
+	TimeTzADT *result = static_cast<TimeTzADT *>(palloc(sizeof(TimeTzADT)));
+	result->time = micros;
+	result->zone = -tz_offset;
```
Comment (JelteF) [inline src/pgduckdb_types.cpp:247]: Why use `-` in this line? That's unexpected enough that I think it deserves a comment.

**Review by JelteF — APPROVED** [review]
Looks good, except for some code comments that should be added for clarity.

File: src/pgduckdb_types.cpp (hunk 1 above)
Comment (dentiny) [reply src/pgduckdb_types.cpp:249]: Totally makes sense, add a comment on how pg/duckdb stores timezone.

**Review by JelteF — APPROVED** [review]
