### PR TITLE
Load icu extension by default

### LINKED ISSUE #490: Certain queries with (TIMESTAMPTZ + INTERVAL) operation fail
### What happens?

I have a DuckDB table with a `TIMESTAMPTZ` column (`time`) attached with pg_duckdb 0.2.0, and certain queries fail when the `WHERE` clause filters on a (`TIMESTAMPTZ` + `INTERVAL`) (addition) operation. This doesn't happen when querying the same data in DuckDB and only happens if an actual table is referenced.

## Example 1
<details>
<summary> Query:</summary>

```sql
select 1
FROM
"ts_public"."measurements"
WHERE  timestamp with time zone '2024-12-10 13:59:59.776896+00' < CAST((NOW() + INTERVAL '1 day') AS date)
LIMIT 1
```

</details>

<details>
  <summary>Output</summary>

```
ERROR:  (PGDuckDB/CreatePlan) Prepared query returned an error: 'Binder Error: No function matches the given name and argument types '+(TIMESTAMP WITH TIME ZONE, INTERVAL)'. You might need to add explicit type casts.
        Candidate functions:
        +(TINYINT) -> TINYINT
        +(TINYINT, TINYINT) -> TINYINT
        +(SMALLINT) -> SMALLINT
        +(SMALLINT, SMALLINT) -> SMALLINT
        +(INTEGER) -> INTEGER
        +(INTEGER, INTEGER) -> INTEGER
        +(BIGINT) -> BIGINT
        +(BIGINT, BIGINT) -> BIGINT
        +(HUGEINT) -> HUGEINT
        +(HUGEINT, HUGEINT) -> HUGEINT
        +(FLOAT) -> FLOAT
        +(FLOAT, FLOAT) -> FLOAT
        +(DOUBLE) -> DOUBLE
        +(DOUBLE, DOUBLE) -> DOUBLE
        +(DECIMAL) -> DECIMAL
        +(DECIMAL, DECIMAL) -> DECIMAL
        +(UTINYINT) -> UTINYINT
        +(UTINYINT, UTINYINT) -> UTINYINT
        +(USMALLINT) -> USMALLINT
        +(USMALLINT, USMALLINT) -> USMALLINT
        +(UINTEGER) -> UINTEGER
        +(UINTEGER, UINTEGER) -> UINTEGER
        +(UBIGINT) -> UBIGINT
        +(UBIGINT, UBIGINT) -> UBIGINT
        +(UHUGEINT) -> UHUGEINT
        +(UHUGEINT, UHUGEINT) -> UHUGEINT
        +(DATE, INTEGER) -> DATE
        +(INTEGER, DATE) -> DATE
        +(INTERVAL, INTERVAL) -> INTERVAL
        +(DATE, INTERVAL) -> TIMESTAMP
        +(INTERVAL, DATE) -> TIMESTAMP
        +(TIME, INTERVAL) -> TIME
        +(INTERVAL, TIME) -> TIME
        +(TIMESTAMP, INTERVAL) -> TIMESTAMP
        +(INTERVAL, TIMESTAMP) -> TIMESTAMP
        +(TIME WITH TIME ZONE, INTERVAL) -> TIME WITH TIME ZONE
        +(INTERVAL, TIME WITH TIME ZONE) -> TIME WITH TIME ZONE
        +(TIME, DATE) -> TIMESTAMP
        +(DATE, TIME) -> TIMESTAMP
        +(TIME WITH TIME ZONE, DATE) -> TIMESTAMP WITH TIME ZONE
        +(DATE, TIME WITH TIME ZONE) -> TIMESTAMP WITH TIME ZONE
        +(ANY[], ANY[]) -> ANY[]

LINE 1: ...0'::timestamp with time zone < ((now() + '1 day'::interval))::date) LIMIT 200
```
</details>

## Example 2 (success)
<summary>Query</summary>
<details>

```sql
select  timestamp with time zone '2024-12-10 13:59:59.776896+00' < CAST((NOW() + INTERVAL '1 day') AS date);
```
</details>
<summary>Output</summary>
<details>
```
 ?column?
----------
 t
(1 row)
```
</details>

## Example 3 (success)
<summary>Query</summary>
<details>

```sql
SELECT "time"
FROM
"ts_public"."measurements"
WHERE  timestamp with time zone '2024-12-10 13:59:59.776896+00' < CAST(NOW() AS DATE)  + INTERVAL '1 day'
LIMIT 1
;
```
</details>
<summary>Output</summary>
<details>
```
             time
-------------------------------
 2022-08-31 23:51:18.165404+00
(1 row)
```
</details>

### OS:

macOS & Linux

### pg_duckdb Version (if built from source use commit hash):

0.2.0

### Postgres Version (if built from source use commit hash):

17

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a nightly build

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Linux distribution) to reproduce the issue?

- [X] Yes, I have

### PR DESCRIPTION
**Pull request by ritwizsinha**
Fixes comparisons/operators of the `timestamp with timezone` type.

Fixes #490

### CODE REVIEW

**Review by mkaruza — APPROVED** [review]

**Comment by mkaruza** [comment]
Hi @ritwizsinha thank you for PR. Could we add test to check why icu will fix #490 before me do merge?

**Comment by ritwizsinha** [comment]
@mkaruza done

File: test/regression/sql/timestamp_with_interval.sql [hunk 1]
```diff
@@ -0,0 +1,7 @@
+CREATE TABLE recently_created_table(a VARCHAR);
+INSERT INTO recently_created_table VALUES ('latest 1'), ('latest 2'), ('latest 3');
+
+select 1 as result
+FROM recently_created_table
+WHERE  timestamp with time zone '2024-12-10 13:59:59.776896+00' < CAST((NOW() + INTERVAL '1 day') AS date)
+LIMIT 1
```
Comment (mkaruza) [inline test/regression/sql/timestamp_with_interval.sql:7]: It is good practice to drop tables, all resources and restore configuration that are used inside one test. So can you drop table `recently_created_table` when is not needed.

**Review by mkaruza — DISMISSED** [review]

File: test/regression/sql/timestamp_with_interval.sql [hunk 2]
```diff
@@ -0,0 +1,9 @@
+CREATE TABLE recently_created_table(a VARCHAR);
+INSERT INTO recently_created_table VALUES ('latest 1'), ('latest 2'), ('latest 3');
+
+select 1 as result
+FROM recently_created_table
+WHERE  timestamp with time zone '2024-12-10 13:59:59.776896+00' < CAST((NOW() + INTERVAL '1 day') AS date)
+LIMIT 1;
+
+drop table recently_created_table;
```
Comment (JelteF) [inline test/regression/sql/timestamp_with_interval.sql:9]: This is missing a final newline. Could you install EditorConfig and save it again? https://editorconfig.org/

Comment (ritwizsinha) [reply test/regression/sql/timestamp_with_interval.sql]: Done

File: test/regression/sql/timestamp_with_interval.sql (hunk 1 above)
Comment (ritwizsinha) [reply test/regression/sql/timestamp_with_interval.sql]: Done

**Review by JelteF — APPROVED** [review]
