### PR TITLE
Fix memory leak for JSON/LIST type during Postgres table scan

### LINKED ISSUE #750: Memory leak when scanning postgres table with jsonb & list type
### What happens?

When converting Postgres tuples to DuckDB chunk data, we reuse some PG functions (e.g., `JsonbToCString` and `deconstruct_array`). These functions internally allocate memory via `palloc` that isn't explicitly freed. This memory leaks until the end of query (when it is released with the ExecutorState).

Possible fixes:
1) Implement custom version of `JsonbToCString` and `deconstruct_array` in pgduckdb. However, this approach might be boverse and introduce compatibility issue.
2) Switch to a dedicated MemoryContext before calling these functions, then periodically reset memory context to reclaim memory (e.g., based on the MemoryContext's allocated memory)

### To Reproduce

```
set duckdb.force_execution=on;

create table j1(c jsonb);
insert into j1 select '{"aasdkjhzxcuyaisdyasuidqwe": 1, "b12314jhkjahsdjkahsdjk": 2}'::jsonb from generate_series(1, 10000000);
-- memory keeps growing
select * from j1 order by 1 limit 1; 

create table a1(c text[]);
insert into a1 select array['aasdkjhzxcuyaisdyasuidqwe', 'b12314jhkjahsdjkahsdjk'] from generate_series(1, 10000000);
-- memory keeps growing
select * from a1 order by 1 limit 1; 
```

### OS:

centos

### pg_duckdb Version (if built from source use commit hash):

main branch

### Postgres Version (if built from source use commit hash):

17

### Hardware:

_No response_

### Full Name:

Yuwei XIAO

### Affiliation:

zbyte-inc

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a source build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [x] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Linux distribution) to reproduce the issue?

- [x] Yes, I have

### PR DESCRIPTION
**Pull request by YuweiXiao**
Fixes #750

### CODE REVIEW

**Comment by YuweiXiao** [comment]
Hey @JelteF, to establish a clear functional boundary for the memory context, I keep it scoped within PostgresScan and initialize & reset it alongside the scan's global state.

**Comment by YuweiXiao** [comment]
It seems the pycheck regression also failed on my local build with the main branch :(

File: src/scan/postgres_scan.cpp [hunk 1]
```diff
@@ -267,8 +284,13 @@ PostgresScanTableFunction::PostgresScanFunction(duckdb::ClientContext &, duckdb:
 
 		SlotGetAllAttrs(slot);
 		InsertTupleIntoChunk(output, local_state, slot);
+
+		if (MemoryContextMemAllocated(duckdb_pg_scan_memory_ctx, false) > 8 * 1024 * 1024L) {
+			MemoryContextReset(duckdb_pg_scan_memory_ctx);
+		}
```
Comment (JelteF) [inline src/scan/postgres_scan.cpp:290]: Is this one really needed? I'd rather keep it simple and only do the reset after we are done with the vector. Doing stuff with duckdb is always at the vector level. Then we also don't have to find a decent magic value, like the 8MB you use now.

File: src/scan/postgres_scan.cpp [hunk 2]
```diff
@@ -170,10 +182,15 @@ PostgresScanGlobalState::PostgresScanGlobalState(Snapshot _snapshot, Relation _r
 	ConstructTableScanQuery(input);
 	table_reader_global_state =
 	    duckdb::make_shared_ptr<PostgresTableReader>(scan_query.str().c_str(), count_tuples_only);
+	duckdb_pg_scan_memory_ctx =
+	    AllocSetContextCreate(CurrentMemoryContext, "DuckDBPerTupleContext", ALLOCSET_DEFAULT_MINSIZE,
+	                          ALLOCSET_DEFAULT_INITSIZE, ALLOCSET_DEFAULT_MAXSIZE);
```
Comment (JelteF) [inline src/scan/postgres_scan.cpp:187]: This is incorrect. Every postgres scan will now create a separate memory context, which they all assign to the same global variable. The cleanup to set to nullptr is also dangerous, if one scan finishes before another. I think what would be better is to do the following:
1. Storing this context actually in the "global state" of the scan, instead of storing it into a process global variable.
2. Switch to this context right after we take the `GlobalProcessLock` in `PostgresScanFunction`, and switching back right before we release it.

Also the name of the context could be improved imo
```suggestion
	duckdb_pg_scan_memory_ctx =
	    AllocSetContextCreate(CurrentMemoryContext, "DuckdbScanContext", ALLOCSET_DEFAULT_MINSIZE,
	                          ALLOCSET_DEFAULT_INITSIZE, ALLOCSET_DEFAULT_MAXSIZE);
```

File: src/pgduckdb_types.cpp [hunk 3]
```diff
@@ -1505,11 +1507,16 @@ AppendString(duckdb::Vector &result, Datum value, idx_t offset, bool is_bpchar)
...
 	auto jsonb = DatumGetJsonbP(value);
-	auto jsonb_str = JsonbToCString(NULL, &jsonb->root, VARSIZE(jsonb));
-	duckdb::string_t str(jsonb_str);
+	StringInfo str = makeStringInfo();
+	auto json_str = JsonbToCString(str, &jsonb->root, VARSIZE(jsonb));
 	auto data = duckdb::FlatVector::GetData<duckdb::string_t>(result);
-	data[offset] = duckdb::StringVector::AddString(result, str);
+	data[offset] = duckdb::StringVector::AddString(result, json_str, str->len);
+	pfree(str->data);
+	pfree(str);
```
Comment (JelteF) [inline src/pgduckdb_types.cpp:1518]: Is this still needed? If not, let's keep this simple and just rely on the memory context resets.

**Review by JelteF — CHANGES_REQUESTED** [review]

File: src/scan/postgres_scan.cpp (hunk 2 above)
Comment (YuweiXiao) [reply src/scan/postgres_scan.cpp:187]: ah yes, you're right.

File: src/scan/postgres_scan.cpp (hunk 1 above)
Comment (YuweiXiao) [reply src/scan/postgres_scan.cpp:290]: Yes, let's simplify by removing it. I was concerned about the wide table or large JSON columns. For example, a single JSON row can be several MB in size, and 2048 such rows would quickly consume a lot of memory. However, in this case, the DuckDB data chunk itself also consumes a significant amount of memory.

File: src/scan/postgres_scan.cpp [hunk 4]
```diff
@@ -11,6 +11,12 @@
 
 #include <numeric> // std::accumulate
 
+extern "C" {
+#include "postgres.h"
+
+#include "utils/memutils.h"
+}
+
```
Comment (JelteF) [inline src/scan/postgres_scan.cpp:19]: Instead of inlcuding postgres headers here (in a file that we managed to remove all postgres includes from). Let's create some basic wrapper functions in a new file in `src/pg/`, maybe called `memory.cpp`. Also `AllocSetContextCreate` and `MemoryContextReset` need to be wrapped in a `PostgresFunctionGuard` when doing so.

File: src/pgduckdb_types.cpp [hunk 5]
```diff
@@ -1506,10 +1506,10 @@ AppendString(duckdb::Vector &result, Datum value, idx_t offset, bool is_bpchar)
 static void
 AppendJsonb(duckdb::Vector &result, Datum value, idx_t offset) {
 	auto jsonb = DatumGetJsonbP(value);
-	auto jsonb_str = JsonbToCString(NULL, &jsonb->root, VARSIZE(jsonb));
-	duckdb::string_t str(jsonb_str);
+	StringInfo str = makeStringInfo();
+	auto json_str = JsonbToCString(str, &jsonb->root, VARSIZE(jsonb));
```
Comment (JelteF) [inline src/pgduckdb_types.cpp:1510]: nice change to remove the additional copy. This change does make me realize that we need to wrap AppendJsonb in a PostgresFunctionGuard. And probably we need the same for the list one, since that uses also allocates right?

Comment (JelteF) [reply src/pgduckdb_types.cpp:1510]: Actually it doesn't seem to save an additional copy. AddString internally will still create a duckdb::string_t out of the `json_str` + `str->len`. But it does save an additional `strlen`, so this still seems like a good change.

**Review by JelteF — CHANGES_REQUESTED** [review]
CI is failing (and see rest of my comments).

File: src/pgduckdb_types.cpp (hunk 5 above)
Comment (YuweiXiao) [reply src/pgduckdb_types.cpp:1510]: I believe we saved one copy of the string. The conversion steps are as follows:

1. `JsonBToString` creates the string buffer.
2. `duckdb::string_t str(jsonb_str);` duplicates the string buffer into a C++ string.
3. `AppendString` performs the string -> string copy internally.

With this PR, step 2 is eliminated. For LIST conversion, I wrap the PostgreSQL function with the guard. Do you think we need a separate function, perhaps `AppendList`?

File: src/scan/postgres_scan.cpp (hunk 4 above)
Comment (YuweiXiao) [reply src/scan/postgres_scan.cpp:19]: good point!

**Comment by YuweiXiao** [comment]
The CI passed in my local run with the latest change. Could you please trigger the pipeline, @JelteF ? Thank you!

**Review by JelteF — APPROVED** [review]
