### PR TITLE
Correctly populate targetlist of CustomScan

### LINKED ISSUE #465: Stack depth limit exceeded when using explain verbose
### What happens?

Stack depth limit exceeded when using explain verbose
0245ee83d25c14791802b4c096b4c38

### To Reproduce

```plpgsql
SET duckdb.force_execution = true;
CREATE TABLE ta(a INT);
EXPLAIN VERBOSE SELECT * FROM ta;
``` 

### OS:

centos8

### pg_duckdb Version (if built from source use commit hash):

main

### Postgres Version (if built from source use commit hash):

16.6

### Hardware:

_No response_

### Full Name:

Man Zeng

### Affiliation:

Halo

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a source build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Linux distribution) to reproduce the issue?

- [X] Yes, I have

### PR DESCRIPTION
**Pull request by JelteF**
`EXPLAIN VERBOSE` was erroring out when the plan contained one of our `CustomScan` nodes. The reason for this was that we were not populating the `targetlist` and `custom_scan_tlist` fields in a way that PG understood so it was recursing infinitely into the same function. This changes how we populate those fields to match what PG expects.

Sadly the additional info in the plan is currently not super useful, and arguably wrong. It will always show the following line in the explain plan.
```
   Output: duckdb_scan.explain_key, duckdb_scan.explain_value
```

To fix that we shouldn't include the EXPLAIN part when sending it to DuckDB for initial planning. Sadly that then breaks the code that we use for executing the query. So for now we're happy with not throwing an error, and that we're populating `targetlist` correctly (which might have some more benefits that we didn't know of).

Fixes #465
Fixes #466
Fixes #463

### CODE REVIEW

File: src/pgduckdb_planner.cpp [hunk 1]
```diff
@@ -87,14 +87,23 @@ CreatePlan(Query *query, bool throw_error) {
 
 		typtup = (Form_pg_type)GETSTRUCT(tp);
 
-		Var *var = makeVar(INDEX_VAR, i + 1, postgresColumnOid, typtup->typtypmod, typtup->typcollation, 0);
+		/* We fill in the varno later, once we know the index of the custom RTE
+		 * that we create. We'll know this at the end of DuckdbPlanNode. This
+		 * can probably be simplified when we don't call the standard_planner
+		 * anymore innside DuckdbPlanNodei, because then we only need a single
```
Comment (Y--) [inline src/pgduckdb_planner.cpp:93]: vim user detected :-)
```suggestion
		 * anymore innside DuckdbPlanNode, because then we only need a single
```

**Review by Y-- — APPROVED** [review]
LGTM!
