### PR TITLE
Use correct output column id list for query processing 

### LINKED ISSUE #190: Equality comparison with varchar crashes
The following SQL consistently produces a crash on my machine. Looking at debugger some memory is clearly uninitialized/freed because it is repeating the `\xa5` byte over and over again.

```sql
create table t(a varchar);
insert into t values('t1');
set duckdb.execution = true;
select count(*) from t where a = 't1';
```

Possibly related to #189

### PR DESCRIPTION
**Pull request by mkaruza**
* When reading postgres tables we need to know which columns need to to
  written to output vector. Based on filtering and query we need to
  either get this information from `projection_ids` or `columns_ids`
  list. Projection ids list will be used when that are fetched columns
  from table but those columns are not needed in further query processing.
  Otherwise columns_ids list will be used.
* Fixes #190

### CODE REVIEW

File: test/regression/sql/query_filter.sql [hunk 1]
```diff
@@ -10,3 +10,10 @@ SELECT COUNT(*) = 2 FROM query_filter_float WHERE a <= 1.0;
 SELECT COUNT(*) = 2 FROM query_filter_float WHERE a < 1.1;
 
 DROP TABLE query_filter_float;
+
+CREATE TABLE query_filter_varchar(a VARCHAR);
+INSERT INTO query_filter_varchar VALUES ('t1'), ('t2'), ('t1');
+SELECT COUNT(*) = 2 FROM query_filter_varchar WHERE a = 't1';
+SELECT COUNT(a) = 2 FROM query_filter_varchar WHERE a = 't1';
```
Comment (JelteF) [inline test/regression/sql/query_filter.sql:17]: Same suggestion about returning the actual count as in #194

File: src/scan/postgres_scan.cpp [hunk 2]
```diff
@@ -44,11 +44,11 @@ PostgresScanGlobalState::InitGlobalState(duckdb::TableFunctionInitInput &input)
 
 	if (input.CanRemoveFilterColumns()) {
 		for (duckdb::idx_t i = 0; i < input.projection_ids.size(); i++) {
-			m_projections[i] = input.column_ids[input.projection_ids[i]];
+			m_column_selection[i] = input.column_ids[input.projection_ids[i]];
 		}
 	} else {
-		for (duckdb::idx_t i = 0; i < input.projection_ids.size(); i++) {
```
Comment (JelteF) [inline src/scan/postgres_scan.cpp:50]: Just to be clear, this line contains the fix right? the rest of the PR is  just doing a field rename.

File: include/pgduckdb/scan/postgres_scan.hpp [hunk 3]
```diff
@@ -24,7 +24,7 @@ class PostgresScanGlobalState {
 	std::mutex m_lock; // Lock for one replacement scan
 	bool m_count_tuples_only;
 	duckdb::map<duckdb::idx_t, duckdb::idx_t> m_columns;
-	duckdb::map<duckdb::idx_t, duckdb::idx_t> m_projections;
+	duckdb::map<duckdb::idx_t, duckdb::idx_t> m_column_selection;
```
Comment (JelteF) [inline include/pgduckdb/scan/postgres_scan.hpp:27]:
```suggestion
	duckdb::map<duckdb::idx_t, duckdb::column_t> m_column_selection;
```

**Review by JelteF — CHANGES_REQUESTED** [review]

File: src/scan/postgres_scan.cpp [hunk 4]
```diff
@@ -44,11 +44,11 @@ PostgresScanGlobalState::InitGlobalState(duckdb::TableFunctionInitInput &input)
 
 	if (input.CanRemoveFilterColumns()) {
 		for (duckdb::idx_t i = 0; i < input.projection_ids.size(); i++) {
```
Comment (JelteF) [inline src/scan/postgres_scan.cpp:46]: Should this be changed to column_ids too?
```suggestion
		for (duckdb::idx_t i = 0; i < input.column_ids.size(); i++) {
```

File: src/scan/postgres_scan.cpp [hunk 5]
```diff
@@ -44,11 +44,11 @@ PostgresScanGlobalState::InitGlobalState(duckdb::TableFunctionInitInput &input)
 
 	if (input.CanRemoveFilterColumns()) {
```
Comment (JelteF) [inline src/scan/postgres_scan.cpp:45]: I think adding some comments to this section would be very helpful. It's not super clear to me what the differences between these branches is (primarily because the comments in duckdb itself on the relevant functions and fields are non-existing).

File: src/pgduckdb_types.cpp [hunk 6]
```diff
@@ -982,12 +982,18 @@ InsertTupleIntoChunk(duckdb::DataChunk &output, duckdb::shared_ptr<PostgresScanG
...
 	/* FIXME: all calls to duckdb_malloc/duckdb_free should be changed in future */
-	Datum *values = (Datum *)duckdb_malloc(sizeof(Datum) * scan_global_state->m_columns.size());
-	bool *nulls = (bool *)duckdb_malloc(sizeof(bool) * scan_global_state->m_columns.size());
+	Datum *values = (Datum *)duckdb_malloc(sizeof(Datum) * scan_global_state->m_output_columns_ids.size());
+	bool *nulls = (bool *)duckdb_malloc(sizeof(bool) * scan_global_state->m_read_columns_ids.size());
 
 	bool valid_tuple = true;
 
-	for (auto const &[columnIdx, valueIdx] : scan_global_state->m_columns) {
+	/* First we are fetching all required columns oredered by column id
```
Comment (JelteF) [inline src/pgduckdb_types.cpp:990]:
```suggestion
	/* First we are fetching all required columns ordered by column id
```

File: test/regression/expected/query_filter.out [hunk 7]
```diff
@@ -28,3 +28,51 @@ SELECT COUNT(*) FROM query_filter_float WHERE a < 1.1;
...
+-- Projection ids list will be used (column `a`is not needed after scan)
+SELECT b FROM query_filter_output_column WHERE a = 2;
+ b  
+----
+ t1
+ t2
+(2 rows)
+
+-- Column ids list used because both of fetched column are used after scan
+SELECT a, b FROM query_filter_output_column WHERE b = 't1';
```
Comment (JelteF) [inline test/regression/expected/query_filter.out:63]: From your comments and my closer reading of the relevant duckdb code, we are expected to change the handle the column order changes. So let's include that in one of these tests
```suggestion
-- Column ids list used because both of fetched column are used after scan, we also should swap column order correctly
SELECT b, a FROM query_filter_output_column WHERE b = 't1';
```

File: src/scan/postgres_scan.cpp (hunk 4 above)
Comment (JelteF) [reply src/scan/postgres_scan.cpp:52]: Turns out the answer is no

File: test/regression/expected/query_filter.out (hunk 7 above)
Comment (JelteF) [reply test/regression/expected/query_filter.out:63]: Let's also add a test where we only re-order columns, but still output all of them.

**Review by JelteF — DISMISSED** [review]
Overall I think this looks pretty good.

File: src/scan/postgres_scan.cpp (hunk 4 above)
Comment (mkaruza) [reply src/scan/postgres_scan.cpp:52]: In this branch, we need to use projection_ids list.

**Review by JelteF — APPROVED** [review]

**Comment by Tishj** [comment]
I get this crash on `main`, likely related to this PR?

```
➜  pg_duckdb git:(main) ✗ psql postgres
 pg_backend_pid 
----------------
          29479
(1 row)

DROP EXTENSION
psql:/Users/thijs/.psqlrc:3: WARNING:  To actually execute queries using DuckDB you need to run "SET duckdb.execution TO true;"
CREATE EXTENSION
SET
psql (16.0)
Type "help" for help.

postgres=# SELECT a, c FROM query_filter_output_column WHERE b = 't1';
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
The connection to the server was lost. Attempting reset: Failed.
!?> 
```
